from __future__ import annotations

from string import Formatter
from typing import Any, Iterable, Mapping

GENERIC_TEMPLATE_VARS: tuple[str, ...] = (
    "artist",
    "title",
    "username",
    "user",
    "channel",
    "points",
    "currency_plural",
    "currency_singular",
    "word",
    "error",
)

MESSAGE_ALLOWED_EXTRA_VARS: dict[str, tuple[str, ...]] = {
    "random_not_found": ("keyword",),
    "playlist_request_added": ("playlist",),
    "playlist_not_found": ("identifier",),
    "playlist_song_missing": ("identifier", "index"),
    "prioritize_success": ("request_id",),
    "remove_success": ("request_id",),
    "played_next": ("next_artist", "next_title", "next_user"),
    "award_gift_sub": ("count",),
    "award_bits": ("amount",),
    "queue_position_changed": ("request_id", "old_position", "new_position"),
    "action_failed_debug": ("action",),
}


class TemplateValidationError(ValueError):
    """Raised when a template references placeholders outside the allowlist."""


def extract_template_placeholders(template: str) -> set[str]:
    """Return all placeholder names found in a format-string template.

    Dependencies: uses ``string.Formatter().parse`` from the Python standard
    library.
    Code customers: template save validation and safe message rendering paths in
    backend and bot runtimes.
    Used variables/origin: ``template`` is DB- or config-sourced template text
    that may include optional format specs/conversions.
    """

    names: set[str] = set()
    for _, field_name, _, _ in Formatter().parse(template):
        if not field_name:
            continue
        if any(symbol in field_name for symbol in (".", "[", "]")):
            raise TemplateValidationError(f"unsupported placeholder syntax: {{{field_name}}}")
        names.add(field_name)
    return names


def build_settings_template_vars(settings_values: Mapping[str, Any] | None) -> dict[str, Any]:
    """Build ``settings_*`` template vars from channel settings mappings.

    Dependencies: pure mapping transformation (no IO).
    Code customers: backend and bot template render/validation helpers.
    Used variables/origin: ``settings_values`` comes from ``ChannelSettings``
    model fields or cached channel settings JSON payloads.
    """

    resolved: dict[str, Any] = {}
    if not settings_values:
        return resolved
    for key, value in settings_values.items():
        resolved[f"settings_{key}"] = "" if value is None else value
    return resolved


def build_allowed_template_vars(
    *,
    message_id: str,
    settings_values: Mapping[str, Any] | None,
    allowed_extra_vars: Iterable[str] | None = None,
) -> set[str]:
    """Build the allowed placeholder set for one catalog ``message_id``.

    Dependencies: combines ``GENERIC_TEMPLATE_VARS``, message-specific extras,
    and dynamic ``settings_*`` keys generated by
    ``build_settings_template_vars``.
    Code customers: API-time template validation and runtime-safe formatters.
    Used variables/origin: ``message_id`` is catalog metadata identity;
    ``settings_values`` provides persisted channel settings keys.
    """

    allowed = set(GENERIC_TEMPLATE_VARS)
    allowed.update(MESSAGE_ALLOWED_EXTRA_VARS.get(message_id, ()))
    if allowed_extra_vars:
        allowed.update(str(name) for name in allowed_extra_vars if str(name).strip())
    allowed.update(build_settings_template_vars(settings_values).keys())
    return allowed


def validate_template_placeholders(template: str, allowed_vars: set[str]) -> None:
    """Validate that template placeholders are all present in ``allowed_vars``.

    Dependencies: uses ``extract_template_placeholders``.
    Code customers: channel bot message save/update endpoints.
    Used variables/origin: ``template`` is API payload text and
    ``allowed_vars`` is the per-message context allowlist.
    """

    unknown = sorted(name for name in extract_template_placeholders(template) if name not in allowed_vars)
    if unknown:
        raise TemplateValidationError(f"unknown placeholders: {', '.join(unknown)}")


def safe_format_template(template: str, template_vars: Mapping[str, Any], allowed_vars: set[str]) -> str:
    """Render templates with deterministic missing/optional variable fallback.

    Dependencies: uses ``extract_template_placeholders`` and Python
    ``str.format_map``.
    Code customers: backend webhook announcements/replies and bot chat
    `_send_catalog_message` runtime path.
    Used variables/origin: ``template_vars`` come from command/event payloads;
    missing placeholders resolve to an empty string for stable rendering.
    """

    validate_template_placeholders(template, allowed_vars)
    resolved = {name: "" for name in allowed_vars}
    for key, value in template_vars.items():
        if key in allowed_vars:
            resolved[key] = "" if value is None else value
    return template.format_map(resolved)
